apiVersion: v1
kind: ConfigMap
metadata:
  namespace: app-wordpress
  name: nginx-vhost-wordpress
data:
  wordpress.conf: |
    server {
      listen 0.0.0.0:80;
      server_name example.blog www.example.blog;
      root /app;
      index index.htm index.html;
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-wordpress
data:
  WORDPRESS_DB_HOST: mysql.default.svc.cluster.local:30306
  WORDPRESS_DB_USER: user
  WORDPRESS_DB_PASSWORD: password
  WORDPRESS_DB_NAME: dbname
