apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: wordpress-wp
  namespace: app-wordpress
  name: pvc-wordpress-wp
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      service: wordpress-wp
