apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    service: wordpress-wp
  namespace: app-wordpress
  name: pv-wordpress-wp
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/www/example_blog/wp-content
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/role
          operator: In
          values:
          - node
