apiVersion: v1
kind: ConfigMap
metadata:
  namespace: app-example
  name: nginx-vhost-example
data:
  example.conf: |
    server {
      listen 0.0.0.0:8080;
      server_name example.com www.example.com;
      root /app;
      index index.htm index.html;
    }
