apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: static-example
  namespace: app-example
  name: pvc-static-example
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Mi
  storageClassName: local-storage
  selector:
    matchLabels:
      service: static-example
